#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
update_incar_kpoints.py
Update INCAR and KPOINTS with improved settings for twisted TMDC study
"""

from __future__ import print_function
import os
import sys

# ============================================================
# IMPROVED SETTINGS
# ============================================================

# Step 0: Full relaxation INCAR
incar_step0_relaxation = {
    'SYSTEM': 'MoSSe-WSSe 0deg full relaxation',
    
    # Electronic structure
    'PREC': 'Accurate',          # CHANGED from Normal
    'ENCUT': 520,                # CHANGED from 400
    'EDIFF': 1e-6,
    'ALGO': 'Normal',
    'NELM': 150,
    
    # Ionic relaxation
    'IBRION': 2,
    'NSW': 300,                  # CHANGED from 200
    'EDIFFG': -0.01,            # CHANGED from -0.02
    'POTIM': 0.2,               # ADDED for stability
    
    # Cell relaxation
    'ISIF': 3,                  # CRITICAL: CHANGED from 2!
    'PSTRESS': 0.0,             # ADDED
    
    # Spin polarization
    'ISPIN': 2,                 # ADDED
    'MAGMOM': '25*2.0 25*2.0 100*0.0',  # ADDED - adjust based on species
    
    # vdW correction
    'IVDW': 12,                 # CRITICAL: ADDED DFT-D3(BJ)!
    
    # k-space integration
    'ISMEAR': 0,
    'SIGMA': 0.05,              # CHANGED from 0.1
    
    # Accuracy
    'LASPH': '.TRUE.',
    'LMAXMIX': 4,
    'ADDGRID': '.TRUE.',
    
    # Mixing
    'AMIX': 0.2,
    'BMIX': 0.0001,
    'AMIX_MAG': 0.8,            # ADDED
    'BMIX_MAG': 0.0001,         # ADDED
    'MAXMIX': 40,
    
    # Precision
    'LREAL': '.FALSE.',
    
    # Output
    'LORBIT': 11,
    'LWAVE': '.FALSE.',
    'LCHARG': '.FALSE.',
    'NWRITE': 2,
    'NCORE': 4,
}

# KPOINTS for step 0
kpoints_step0 = {
    'comment': 'Automatic mesh for 5x5 supercell relaxation',
    'mode': 'Gamma',
    'mesh': [3, 3, 1],          # CHANGED from [2, 2, 1]
    'shift': [0, 0, 0],
}

# ============================================================
# FUNCTIONS
# ============================================================

def write_incar(filename, incar_dict):
    """Write INCAR file from dictionary"""
    with open(filename, 'w') as f:
        f.write("# " + "=" * 58 + "\n")
        f.write("# INCAR for Twisted Janus TMDC Heterostructure\n")
        f.write("# Step 0: Full relaxation (ISIF=3)\n")
        f.write("# Generated by update_incar_kpoints.py\n")
        f.write("# " + "=" * 58 + "\n")
        f.write("\n")
        
        # Group by category
        categories = [
            ('System', ['SYSTEM']),
            ('Electronic Structure', ['PREC', 'ENCUT', 'EDIFF', 'ALGO', 'NELM']),
            ('Ionic Relaxation', ['IBRION', 'NSW', 'EDIFFG', 'POTIM']),
            ('Cell Relaxation', ['ISIF', 'PSTRESS']),
            ('Spin Polarization', ['ISPIN', 'MAGMOM']),
            ('vdW Correction', ['IVDW']),
            ('k-space Integration', ['ISMEAR', 'SIGMA']),
            ('Accuracy', ['LASPH', 'LMAXMIX', 'ADDGRID']),
            ('Mixing', ['AMIX', 'BMIX', 'AMIX_MAG', 'BMIX_MAG', 'MAXMIX']),
            ('Precision', ['LREAL']),
            ('Output', ['LORBIT', 'LWAVE', 'LCHARG', 'NWRITE', 'NCORE']),
        ]
        
        for cat_name, keys in categories:
            f.write("# ===== {0} =====\n".format(cat_name))
            for key in keys:
                if key in incar_dict:
                    val = incar_dict[key]
                    if isinstance(val, bool):
                        val_str = '.TRUE.' if val else '.FALSE.'
                    elif isinstance(val, float):
                        if abs(val) < 0.01 and val != 0:
                            val_str = "{0:.2E}".format(val)
                        else:
                            val_str = str(val)
                    else:
                        val_str = str(val)
                    
                    f.write("{0:12s} = {1}\n".format(key, val_str))
            f.write("\n")

def write_kpoints(filename, kpoints_dict):
    """Write KPOINTS file"""
    with open(filename, 'w') as f:
        f.write(kpoints_dict['comment'] + "\n")
        f.write("0\n")
        f.write(kpoints_dict['mode'] + "\n")
        mesh = kpoints_dict['mesh']
        f.write("{0} {1} {2}\n".format(mesh[0], mesh[1], mesh[2]))
        shift = kpoints_dict['shift']
        f.write("{0} {1} {2}\n".format(shift[0], shift[1], shift[2]))

def update_directory(dirname):
    """Update INCAR and KPOINTS in a directory"""
    
    print("  Updating: {0}".format(dirname))
    
    # Backup original files
    for fname in ['INCAR', 'KPOINTS']:
        orig = os.path.join(dirname, fname)
        backup = os.path.join(dirname, fname + '.original')
        
        if os.path.exists(orig) and not os.path.exists(backup):
            os.rename(orig, backup)
            print("    Backed up: {0} -> {1}".format(fname, fname + '.original'))
    
    # Adjust MAGMOM based on POSCAR
    poscar_path = os.path.join(dirname, 'POSCAR')
    if os.path.exists(poscar_path):
        with open(poscar_path, 'r') as f:
            lines = f.readlines()
            species = lines[5].split()
            counts = list(map(int, lines[6].split()))
            
            # Generate MAGMOM string
            magmom_parts = []
            for sp, count in zip(species, counts):
                if sp in ['Mo', 'W']:
                    # Initial magnetic moment for transition metals
                    magmom_parts.append("{0}*2.0".format(count))
                else:
                    # No magnetic moment for S, Se
                    magmom_parts.append("{0}*0.0".format(count))
            
            magmom_str = " ".join(magmom_parts)
            print("    MAGMOM: {0}".format(magmom_str))
            
            # Update INCAR dict
            incar_dict = incar_step0_relaxation.copy()
            incar_dict['MAGMOM'] = magmom_str
    else:
        print("    Warning: POSCAR not found, using default MAGMOM")
        incar_dict = incar_step0_relaxation.copy()
    
    # Write new files
    write_incar(os.path.join(dirname, 'INCAR'), incar_dict)
    print("    Created: INCAR")
    
    write_kpoints(os.path.join(dirname, 'KPOINTS'), kpoints_step0)
    print("    Created: KPOINTS")
    
    print("    Success!\n")

def show_changes():
    """Show what will be changed"""
    print("=" * 60)
    print("INCAR/KPOINTS Update Summary")
    print("=" * 60)
    print()
    print("CRITICAL CHANGES:")
    print("  1. ISIF: 2 -> 3 (ENABLE CELL OPTIMIZATION)")
    print("  2. IVDW: (none) -> 12 (ADD vdW CORRECTION)")
    print("  3. ISPIN: (none) -> 2 (ADD SPIN POLARIZATION)")
    print()
    print("IMPORTANT CHANGES:")
    print("  4. PREC: Normal -> Accurate")
    print("  5. ENCUT: 400 -> 520 eV")
    print("  6. EDIFFG: -0.02 -> -0.01 eV/A")
    print("  7. NSW: 200 -> 300")
    print("  8. SIGMA: 0.1 -> 0.05 eV")
    print("  9. KPOINTS: 2x2x1 -> 3x3x1")
    print()
    print("ADDITIONS:")
    print(" 10. MAGMOM: Added (spin initialization)")
    print(" 11. POTIM: 0.2 (smaller steps)")
    print(" 12. PSTRESS: 0.0 (target pressure)")
    print(" 13. AMIX_MAG, BMIX_MAG: Added")
    print()
    print("=" * 60)
    print()

# ============================================================
# MAIN
# ============================================================

def main():
    """Main function"""
    
    show_changes()
    
    # Find all calculation directories
    calc_dirs = [d for d in os.listdir('.') 
                 if os.path.isdir(d) and d.startswith('MoSSe_') and '__WSSe_' in d]
    
    if not calc_dirs:
        print("ERROR: No calculation directories found!")
        print("Looking for: MoSSe_*__WSSe_*")
        sys.exit(1)
    
    print("Found {0} directories:".format(len(calc_dirs)))
    for d in sorted(calc_dirs):
        print("  " + d)
    print()
    
    # Ask for confirmation
    try:
        response = raw_input("Update all directories? (y/n): ")  # Python 2
    except NameError:
        response = input("Update all directories? (y/n): ")  # Python 3
    
    if response.lower() != 'y':
        print("Cancelled")
        sys.exit(0)
    
    print()
    print("Updating directories...")
    print()
    
    # Update each directory
    success_count = 0
    for dirname in sorted(calc_dirs):
        try:
            update_directory(dirname)
            success_count += 1
        except Exception as e:
            print("  ERROR in {0}: {1}\n".format(dirname, str(e)))
    
    print("=" * 60)
    print("Updated {0}/{1} directories".format(success_count, len(calc_dirs)))
    print("=" * 60)
    print()
    print("Original files saved as:")
    print("  INCAR.original")
    print("  KPOINTS.original")
    print()
    print("Next steps:")
    print("  1. Review changes: diff MoSSe_Se_up__WSSe_S_up/INCAR.original \\")
    print("                          MoSSe_Se_up__WSSe_S_up/INCAR")
    print()
    print("  2. Run final check: ./final_check_before_submit.sh")
    print()
    print("  3. Consider convergence tests BEFORE full relaxation:")
    print("     - K-point convergence (2x2x1 vs 3x3x1 vs 4x4x1)")
    print("     - ENCUT convergence (450, 500, 520, 550 eV)")
    print()
    print("=" * 60)

if __name__ == '__main__':
    main()
